version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20072004
      POSTGRES_DB: finalProject
    ports:
      - 5432:5432
  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server