// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RatingServicerClient is the client API for RatingServicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatingServicerClient interface {
	AddReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error)
}

type ratingServicerClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingServicerClient(cc grpc.ClientConnInterface) RatingServicerClient {
	return &ratingServicerClient{cc}
}

func (c *ratingServicerClient) AddReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error) {
	out := new(Review)
	err := c.cc.Invoke(ctx, "/rating.RatingServicer/AddReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServicerServer is the server API for RatingServicer service.
// All implementations must embed UnimplementedRatingServicerServer
// for forward compatibility
type RatingServicerServer interface {
	AddReview(context.Context, *Review) (*Review, error)
	mustEmbedUnimplementedRatingServicerServer()
}

// UnimplementedRatingServicerServer must be embedded to have forward compatible implementations.
type UnimplementedRatingServicerServer struct {
}

func (UnimplementedRatingServicerServer) AddReview(context.Context, *Review) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReview not implemented")
}
func (UnimplementedRatingServicerServer) mustEmbedUnimplementedRatingServicerServer() {}

// UnsafeRatingServicerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingServicerServer will
// result in compilation errors.
type UnsafeRatingServicerServer interface {
	mustEmbedUnimplementedRatingServicerServer()
}

func RegisterRatingServicerServer(s grpc.ServiceRegistrar, srv RatingServicerServer) {
	s.RegisterService(&RatingServicer_ServiceDesc, srv)
}

func _RatingServicer_AddReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServicerServer).AddReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rating.RatingServicer/AddReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServicerServer).AddReview(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

// RatingServicer_ServiceDesc is the grpc.ServiceDesc for RatingServicer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatingServicer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rating.RatingServicer",
	HandlerType: (*RatingServicerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddReview",
			Handler:    _RatingServicer_AddReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rating.proto",
}
